spring:
  application:
    name: notification-service

#  kafka:
#    streams:
#      bootstrap-servers: localhost:9092
#      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde

  mail:
    host: smtp.gmail.com
    port: 587
    username: jaikaran2021@gmail.com
    password: xfcu vsdz yefz gukv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


#kafka:
#  topics:
#    order: order-notifications
