# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build, test and push to docker user-service

on:
  push:
    branches: [ "main" ]
    paths:
      - "user-service/**"
      - ".github/workflows/build-user-service.yml"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#    - name: Maven dependency sumbmission
#      uses: advanced-security/maven-dependency-submission-action@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: user-service
      run: mvn -B package

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
      with:
        directory: user-service
        ignore-maven-wrapper: true

    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # enables docker to build for all the cpu architecture not only host architecture
    - name: Set up QEMU for docker build for all the architecture
      uses: docker/setup-qemu-action@v3

    # initilizing the docker builder
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v6
      with:
       context: user-service
       push: true
       tags: jaikrn/app:latest


